### ISSUE TITLE
Active Development?

### ISSUE THREAD

**Issue by ilanbiala** [fontello/svg-font-dump#2]
Is this still being actively developed? Not much has happened in the past 5 months. There's no documentation and I want to use this package.

**Comment by puzrin** [comment]
There are no needs to "develop" this project, because it does it's job good enougth.

**Comment by ilanbiala** [comment]
There's no documentation..

**Comment by puzrin** [comment]
This tool was done for internal fontello needs, and has cli help.

I'm not interested to spend time for it and to promote it in any way. Anyone can fork it or make a pull request.
