### ISSUE TITLE
Error dump svg font

### ISSUE THREAD

**Issue by betula** [fontello/svg-font-dump#4]
Thanks, for awesome tool, it's really useful, but I have one little problem.
Source: [weather-icons-1.3.2](https://github.com/erikflowers/weather-icons) [svg font](https://github.com/erikflowers/weather-icons/blob/master/font/weathericons-regular-webfont.svg).
Result icons has incorrect viewBox, for example glyph__f00a.svg:
![2015-05-26 15 10 17](https://cloud.githubusercontent.com/assets/421161/7812253/61d74cb8-03b9-11e5-8a8b-4dabaec1e352.png)
I'll be happy if you can help find a decide this problem.

**Comment by puzrin** [comment]
That's normal, if icon was specially drawn larger than glyph metrict. Original size is kept intact to keep right proportions between other glyphs. You can process those as you wish, for example with calculatin bounding box, but that's not duper's task.
